version: "3.8"

services:
  backend:
    build: ./backend
    container_name: balance_backend_container
    ports:
      - '8080:8080'  # container:host
    volumes:
      - ./backend:/balance_backend
      - /balance_backend/node_modules
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: balance_frontend_container
    ports:
      - '3000:3000'  # container: host
    volumes:
      - ./frontend:/balance_frontend
      - /balance_frontend/node_modules
    stdin_open: true  # these 2 open an interactive shell for react container --> need to look into y its needed
    tty: true

#  database:
#    build: ./database
#    container_name: balance_database_container
#    ports:
#      - '3306:3306'