version: "3.8"

services:
  backend:
    build: ./backend
    container_name: balance_backend_container
    ports:
      - '8080:8080'  # container:host
    volumes:
      - ./backend:/balance_backend
#      - ./backend/node_modules

  frontend:
    build: ./frontend
    container_name: balance_frontend_container
    ports:
      - '3000:3000'  # container: host
    # need the following 2 for react container
    #   opens an interactive shell, gotta look more into why it's needed
    stdin_open: true
    tty: true

#  database:
#    build: ./database
#    container_name: balance_database_container
#    ports:
#      - '3306:3306'