version: "3.8"

services:
    database:
        image: mysql:8.3
        container_name: balance_database_container
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: student_group_db
        ports:
        - "3307:3306"  # host:container
        networks:
        - balance_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        container_name: balance_backend_container
        build: ./backend
        ports:
            - 8080:8080 # container:host
        expose:
            - 8080
        volumes:
            - ./backend:/balance_backend
            - /balance_backend/node_modules
        environment:
            WATCHPACK_POLLING: true # https://stackoverflow.com/a/72661752
            PORT: 8080
            DB_HOST: localhost
            DB_USER: root
            DB_PASSWORD: somethingverysecure
            DB: student_group_db
            AUTH: DEV
        depends_on:
            database:
                condition: service_healthy
        entrypoint: sh -c "sleep 20 && npm start"
        networks:
            - balance_network
        stdin_open: true
        tty: true

    frontend:
        build: ./frontend
        container_name: balance_frontend_container
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/balance_frontend
            - /balance_frontend/node_modules
        environment:
            WATCHPACK_POLLING: true # https://stackoverflow.com/a/72661752
        stdin_open: true # these 2 open an interactive shell for react container --> need to look into y its needed
        tty: true
        networks:
            - balance_network

networks:
    balance_network:
        driver: bridge
